### ISSUE TITLE
annotation file missing

### ISSUE THREAD

**Issue by yfraquelle** [solitaryzero/NIL_EL#1]
I try to run `sh scripts/preprocess/vectorize_no_nil.sh`, an error occurs:

```
Traceback (most recent call last):
  File "preprocess/vectorize.py", line 281, in <module>
    work(args)
  File "preprocess/vectorize.py", line 48, in work
    with open(args.nil_type_path, 'r', encoding='utf-8') as fin:
FileNotFoundError:` [Errno 2] No such file or directory: '../data/NEL_annotation/NEL_annotated.csv'
```

**Comment by solitaryzero** [comment]
I have uploaded the missing annotation file under data/NEL_annotation/NEL_annotated.csv
Sorry for the inconvience.
